name: Build SharpILMixins (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')" 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.2.20479.15'

    - name: Build Annotations
      run: dotnet build SharpILMixins.Annotations -c Release
      
    - name: Pack Annotations
      run: dotnet pack SharpILMixins.Annotations -o . -c Release
      
    - name: Build Processor
      run: dotnet build SharpILMixins.Processor -c Release
      
    - name: Pack Processor
      run: dotnet pack SharpILMixins.Processor -o . -c Release
      
    - name: Build Analyzer
      run: dotnet build Analyzer\SharpILMixins.Analyzer.Package
      
    - name: Pack Analyzer
      run: dotnet pack Analyzer\SharpILMixins.Analyzer.Package -o .

    - name: Pack Project Template
      run: dotnet pack SharpILMixins.Template -o .
            
    - name: Build ProcessorBase
      run: dotnet build SharpILMixins.ProcessorBase -c Release
      
    - name: Pack ProcessorBase
      run: dotnet pack SharpILMixins.ProcessorBase -o . -c Release
      
    - name: NuGet Push Packages
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload NuGet Build Artifacts
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'Built NuGet Packages'
        # A file, directory or wildcard pattern that describes what to upload
        path: '.\*.nupkg'
