name: Build SharpILMixins (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.2.20479.15'
      
    - name: Build Processor (win-x64)
      run: dotnet publish SharpILMixins.Processor -r win-x64 -o publish-out

    - name: Build Annotations
      run: dotnet build SharpILMixins.Annotations
      
    - name: Pack Annotations
      run: dotnet pack SharpILMixins.Annotations -o .
      
    - name: Build Processor
      run: dotnet build SharpILMixins.Processor
      
    - name: Pack Processor
      run: dotnet pack SharpILMixins.Processor -o .
      
    - name: NuGet Push Annotations
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload Publish Build Artifact (win-x64)
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'SharpILMixins.Processor'
        # A file, directory or wildcard pattern that describes what to upload
        path: 'publish-out\*'

    - name: Build Processor (SelfContained win-x64)
      run: dotnet publish SharpILMixins.Processor -r win-x64 -o publish-out2 -p:PublishSingleFile=true
      
    - name: Upload Publish Build Artifact (SelfContained win-x64)
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'SharpILMixins.Processor-SelfContained'
        # A file, directory or wildcard pattern that describes what to upload
        path: 'publish-out2\*'
